defaults: &defaults
  host: 127.0.0.1
  port: 27017
  options:
    w: 1
    pool_size: 1
    slave_ok: false
    ssl: false

production:
  uri: <%= ENV['MONGOHQ_URL'] %>

development:
  <<: *defaults
  database: ritual_recipes_development

test:
  <<: *defaults
  database: ritual_recipes_test
  w: 0

